name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install dependencies
      run: cargo build

    - name: Run tests
      run: cargo test

    - name: Run clippy
      run: cargo clippy -- -D warnings
      if: ${{ success() }}
